#!/usr/bin/env bash
# Generates esp32_firmware/wifi_credentials.h from LEDDITE_SSID / LEDDITE_PASSWORD.
#
# The header is gitignored. Values are never echoed — only the file's shape is
# printed back for confirmation.
#
#   tools/gen-wifi-credentials.sh [path-to-env-file]
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

ENV_FILE="${1:-$HOME/personal.data.adishy.com/tmp/downloads/leddite.sh}"
OUT=esp32_firmware/wifi_credentials.h

if [ -f "$ENV_FILE" ]; then
  set -a; . "$ENV_FILE"; set +a
fi

: "${LEDDITE_SSID:?LEDDITE_SSID not set (export it or pass an env file)}"
: "${LEDDITE_PASSWORD:?LEDDITE_PASSWORD not set}"

cat > "$OUT" <<HDR
#pragma once
// Generated by tools/gen-wifi-credentials.sh from the LEDDITE_* environment.
// gitignored — never commit this file.
const char* WIFI_SSID     = "${LEDDITE_SSID}";
const char* WIFI_PASSWORD = "${LEDDITE_PASSWORD}";
HDR

echo "Wrote $OUT:"
sed -E 's/"[^"]*"/"<redacted>"/g' "$OUT" | sed 's/^/  /'
git check-ignore -q "$OUT" && echo "  gitignored: yes" || echo "  WARNING: not gitignored!"
