#!/usr/bin/env bash
# Writes esp32_firmware/ota_config.h from environment variables without ever
# echoing the password. Mirrors tools/gen-wifi-credentials.sh.
#
#   LEDDITE_OTA_URL   required
#   LEDDITE_OTA_USER  optional (default "leddite")
#   LEDDITE_OTA_PASS  optional (default empty = no auth header)
#   LEDDITE_FW_VERSION optional (default "dev")
#
#   tools/gen-ota-config.sh [path-to-env-file]
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

ENV_FILE="${1:-.env.secrets}"
if [ -f "$ENV_FILE" ]; then
  set -a
  # shellcheck disable=SC1090
  . "$ENV_FILE"
  set +a
fi

: "${LEDDITE_OTA_URL:?set LEDDITE_OTA_URL (e.g. http://192.168.1.50:8000/leddite.bin)}"
OTA_USER="${LEDDITE_OTA_USER:-leddite}"
OTA_PASS="${LEDDITE_OTA_PASS:-}"
FW_VERSION="${LEDDITE_FW_VERSION:-dev}"

OUT=esp32_firmware/ota_config.h
cat > "$OUT" <<HDR
#pragma once
// GENERATED by tools/gen-ota-config.sh — do not commit (see .gitignore).
#define LEDDITE_OTA_URL     "${LEDDITE_OTA_URL}"
#define LEDDITE_OTA_USER    "${OTA_USER}"
#define LEDDITE_OTA_PASS    "${OTA_PASS}"
#define LEDDITE_FW_VERSION  "${FW_VERSION}"
HDR

echo "wrote $OUT (url=${LEDDITE_OTA_URL}, user=${OTA_USER}, version=${FW_VERSION})"
